### ISSUE TITLE
vsBots updates tracker

### ISSUE THREAD

**Issue by Zeisenx** [Zeisenx/vsBots#1]
## High priority
- [x] #2
- [ ] Fix server crashes
    - [ ] Windows
        - [ ] Crash randomly on player death, [crash dump](https://crash.limetech.org/7e5ti2oxtaxr)
    - [ ] Linux
        - [ ] Just crashes instantly on player join to server, not sure which one caused it
        - [ ] Crash on modifying [Boss] damage to 9999

## Medium priority
- [x] #4
- [x] Mapcycle with workshop map
    - [ ] Mapcycle file support with comment, two slashes
    - [ ] Show nextmap name instead of workshop ID on game end
- [x] #3
- [x] Buy command support such like 'buy ak47', 'buy 57'
- [X] Allow healthkit buying via buy command
- [ ] Custom assets support
    - [x] Bullet tracer for [Boss] Crusher
    - [X] Explosion sound & effects for [Boss] Exp203 self-explosion
    - [x] Sound effect on boss kill
    - [ ] Grenade trails
- [ ] Chat commands
    - [ ] !status, !상황 : Displays bots difficulty
    - [ ] !nextmap : Do same function like nextmap in sourcemod
    - [ ] !top5 - Display top 5 on player ranking
- [ ] [Boss] Stone movement improvement on 11 bot level or above
- [ ] [Boss] Stone defuses bomb force even gets hit
- [ ] [Boss] Crusher defuses bomb instantly

## Low priority
- [ ] Make to single timer [Boss] Exp203 self-explosion on death
- [ ] Restart [Boss] Crusher health regen timer on hurt
- [ ] Multi language supports for Taiwan, Japan

**Comment by Zeisenx** [comment]
[1282616760960421920](https://discord.com/channels/1160440421130973216/1282605253279219754/1282616760960421920)
